name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        android-version: [35]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-version: ${{ matrix.android-version }}
          cache: true

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Install dependencies
        run: |
          ./gradlew clean
          ./gradlew dependencies

      - name: Build the project
        run: ./gradlew assembleDebug



      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Start emulator
        run: |
          echo "Starting Android emulator"
          nohup emulator -avd test -no-window -noaudio -gpu off -memory 2048 -accel auto &

      - name: Wait for emulator to start
        run: |
          echo "Waiting for emulator to boot up"
          adb wait-for-device
          adb shell input keyevent 82  # Unlock the emulator screen
  

      - name: Run Instrumented tests (Android tests)
        run: ./gradlew connectedDebugAndroidTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results/testDebugUnitTest

      - name: Upload instrumented test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumented-test-results
          path: app/build/outputs/androidTest-results

